version: "3"

services:
    flasker:
        container_name: flasker-api
        build: .
        volumes:
            - ./logs:/flasker/logs     # Store logs on local drive
        networks:
            - backend
        # Use ports when connecting directly to flask without nginx
        ports:
            - "127.0.0.1:5003:5003"
        environment:
            - "FLASK_ENV=development"
            - "APP_SETTINGS=config.DevelopmentDockerConfig"
        depends_on:
            - postgres

    postgres:
        container_name: flasker-postgres
        image: postgres:11-alpine
        volumes:
            - flasker_postgres_data:/var/lib/postgresql    # Store data here
        networks:
            - backend
        ports:
            - "127.0.0.1:5433:5432"
        #expose:
        #    - "5432"
        environment:
            - "POSTGRES_USER=flasker"
            - "POSTGRES_PASSWORD=wrong-horse-battery-staple"
            - "POSTGRES_DATABASE=flasker"


volumes:
    flasker_postgres_data:


networks:
    backend:
