"""remove user points

Revision ID: 66eaf018048b
Revises: 0d3be47772f8
Create Date: 2019-05-19 20:00:25.990936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66eaf018048b'
down_revision = '0d3be47772f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'points')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('points', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
